### ISSUE TITLE
gcc 13 error in ZVulkan due to missing <cstdio>

### ISSUE THREAD

**Issue by costel78** [dpjudas/ZVulkan#1]
Not yet released gcc 13, does not include automatically cstdio. This lead to compile error on gzdoom, which use ZVulkan.
[gcc13.patch.txt](https://github.com/dpjudas/ZVulkan/files/10661628/gcc13.patch.txt)

I reported the error on GzDoom, but I was recommended to report here. The patch is trivial.
https://github.com/ZDoom/gzdoom/issues/1992

Thank you!

**Comment by costel78** [comment]
The bug is no longer active with gcc-13.2.0. Closing.
Thank you!

**Comment by devnoot** [comment]
FYI I just encountered this  error with gcc-13.2.1. The patch @costel78 wrote fixed it. 

```
❯ gcc --version
gcc (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Eonfge** [comment]
I wish to re-open this issue. It also happens with gcc-13.2.0 as documented here on line `3563`:
https://buildbot.flathub.org/#/builders/9/builds/5884/steps/8/logs/stdio

**Comment by devnoot** [comment]
we already have a patch that seemingly fixes it, is there a reason why it cant be merged in?
